apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka3
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kafka3
  template:
    metadata:
      labels:
        component: kafka3
    spec:
      containers:
      - name: kafka3
        image: wurstmeister/kafka
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
          - containerPort: 9092
        env:
          - name: KAFKA_BROKER_ID
            value: "3"
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zoo1:2181,zoo2:2181,zoo3:2181
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: kaf3
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
            - kaf3

---
apiVersion: v1
kind: Service
metadata:
  name: kaf3
spec:
  selector:
    component: kafka3
  ports:
  - name: kafka3-9092
    port: 9092
    targetPort: 9092
    protocol: TCP