apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper1
  template:
    metadata:
      labels:
        app: zookeeper1
        node: node1
    spec:
      containers:
      - name: zookeeper1
        image: digitalwonderland/zookeeper
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zoo1
        - name: ZOOKEEPER_SERVER_2
          value: zoo2
        - name: ZOOKEEPER_SERVER_3
          value: zoo3
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: zoo1
spec:
  selector:
    app: zookeeper1
    node: node1
  type: ClusterIP
  ports:
  - name: port-2181
    port: 2181
    protocol: TCP
  - name: port-2888
    port: 2888
    protocol: TCP
  - name: port-3888
    port: 3888
    protocol: TCP